name: Run Discord Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install discord.js dotenv

      - name: Run bot
        env:
          IDOS_BOT_TOKEN: ${{ secrets.IDOS_BOT_TOKEN }}
          CLIENT_BOT_IDOS: ${{ secrets.CLIENT_BOT_IDOS }}
        run: node index.js
