name: IDOS to Discord

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-idos-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run bot
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: node idos-discord.js
